### PR TITLE
Add command to run Prefixr

### LINKED ISSUE #5: Command
Missing a command to activate it. I'm bad at remembering keyboard shortcuts.

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #5

### CODE REVIEW

**Comment by sindresorhus** [comment]
@wbond ping?

**Comment by robsonpeixoto** [comment]
Please, merge this feature =D

**Comment by sindresorhus** [comment]
@wbond ping

**Comment by sindresorhus** [comment]
ping

**Comment by addyosmani** [comment]
@wbond is it possible to merge this in?

**Comment by steveoh** [comment]
:thumbsup: please.

**Comment by sindresorhus** [comment]
If anyone looks here, try out [sublime-autoprefixer](https://github.com/sindresorhus/sublime-autoprefixer) instead. It's much faster, works offline, will only add needed prefixes, and more.

**Comment by wbond** [comment]
Yeah, I agree with @sindresorhus - Prefixr is mostly unmaintained. I hasn't been ported to ST3, needs to be online to contact the Prefixr.com API (which sometimes returns bad data), and doesn't work with things like proxies.

Once I get some time to return to it, it may end up being moved to a new maintainer who has the time to work on it.

**Pull request closed without merging**
